### ISSUE TITLE
Learn Polkadot API (Js library)

### ISSUE THREAD

**Issue by syan095** [IRISxiaowang/substrate-bank#12]
Learn about using the Polkadot API js library.
https://polkadot.js.org/docs/api/start/

Write a simple test script that can:
* make a extrinsic call to the chain
* make a RPC call to the chain
* query a chain state.

**Comment by IRISxiaowang** [comment]
Close this issue in xy-chain-frontend project.

026e2a8a1fcd6a1c7bcda93f6b7d3cc098ee6538
