### ISSUE TITLE
Perform a Runtime Upgrade

### ISSUE THREAD

**Issue by syan095** [IRISxiaowang/substrate-bank#19]
learn about what a "runtime upgrade" is and how to perform one.

Create a test branch, and add a new extrinsic in the Roles pallet called "nominate":
* Allows current Manager and Auditor to "nominate" another account to become the same role.
* Only works for Manager and Auditor roles. 

Launch a local testnet using code compiled without the new extrinsic.
Switch to the new version, and compile the new code into WASM.

Observe that the new extrinsic isn't there in the current local testnet.
Perform a "Runtime Upgrade".
Observe that the new extrinsic can be called. Test that it works.

**Comment by IRISxiaowang** [comment]
Runtime Upgrade

make change locally
runtime lib upgrade version:  spec_version: 100,
cargo build --release

find the wasm file in target/release/wbuild/xy-chain-runtime
copy the file to upload

stash the change code and run localnet
// build and run local testnet
cargo build --release
./target/release/xy-chain --dev

go to front-end use root user Alice
select sudo, sudo(call)
system setcodewithoutcheck()
upload the wasm file
submit
